module

-- BEGIN GENERATED VOCABULARY: generated by scripts/challenge-prep.py from the Vocabulary modules; edit those, then run `python3 scripts/challenge-prep.py sync`.
public import Mathlib.Analysis.InnerProductSpace.Laplacian
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Topology.EMetricSpace.Lipschitz
public import Mathlib.Topology.MetricSpace.Holder
public import Mathlib.Topology.UniformSpace.LocallyUniformConvergence

@[expose] public section

-- from Vocabulary.lean
/-!
# Trusted statements: Perron's extremal solutions of the Bernoulli problem

This file imports Mathlib only. It is the complete trusted surface of the `planar-structure`
challenge: `Challenge.lean` and `Solution.lean` both state the three claims below.

## Source

F. Abedin, W. M. Feldman, K. Stinson, *Variational properties of Perron's extremal solutions in
the Bernoulli one-phase problem*, arXiv:2609.14981 (`[AFS]` below).

* `Corollary2DSmallestClaim`, `Corollary2DLargestClaim`: [AFS, Corollary 1.2] (i) and (ii).
* `ModelExampleClaim`: a non-vacuity check (a model example), not a result of the paper. In `ℝ²`
  with `Q ≡ 1`, one domain and one boundary condition give distinct smallest and largest solutions,
  and the smallest one has a two-plane point.

## The problem

The Bernoulli one-phase problem [AFS, (1.1)] in a domain `U ⊆ ℝᵈ`, with coefficient `Q > 0`:
`Δu = 0` in `{u > 0}` and `|∇u| = Q` on `∂{u > 0} ∩ U`, for `u ≥ 0`.

## Standing assumptions

[AFS, §1] assumes throughout: `U ⊆ ℝᵈ`, `d ≥ 2`, is open, bounded and connected with `C²`
boundary, and `Q` is Lipschitz on `Ū` with `0 < Q_min ≤ Q ≤ Q_max` on `Ū`. The claims below state
these as separate hypotheses. The `C²` boundary is encoded by a global defining function
(`HasC2Boundary`), a standard equivalent form.

## Vocabulary

The ambient space is `ℝᵈ = EuclideanSpace ℝ (Fin d)`. All functions are total functions on `ℝᵈ`;
each definition restricts to its domain explicitly, and values outside the domain are never used. Gradients `∇`, Laplacians `Δ` and derivatives are Mathlib's pointwise
ones (`0` at points of non-differentiability, by Mathlib's convention).

* `posSet`, `freeBoundary`: `{u > 0}` and `∂{u > 0} ∩ U`, taken inside `U`.
* `TouchesBelow`, `TouchesAbove`: local, non-strict touching in a set.
* `IsViscSuper`, `IsViscSub`: viscosity super- and subsolutions [AFS, Definition 2.1].
* `IsStrictSub`, `IsStrictSuper`: smooth strict sub- and supersolutions [AFS, Definition 2.2].
* `perronSuperClass`, `perronSmallest`, `perronSubClass`, `perronLargest`: Perron's classes and
  extremal solutions [AFS, (2.1)–(2.4)].
* `blowup`, `IsBlowupLimit`, `IsC1GammaHypersurfaceNear`, `IsClassicalNear`: blow-ups and classical
  solutions near a free boundary point [AFS, Corollary 1.2 and its footnote].

## Differences from the printed paper

Each is stated in the docstring of the definition concerned.

* Test functions in the viscosity definitions are smooth on all of `ℝᵈ` rather than on `U`. This is
  equivalent, since the conditions are local: multiply by a cutoff.
* The data `g` of Definition 2.2 are `C²` on `ℝᵈ` rather than on `Ū`. A `C²(Ū)` function on a
  `C²` domain extends to a `C²(ℝᵈ)` function.
-/


noncomputable section

open Set Filter Topology Metric
open scoped ContDiff Gradient Laplacian NNReal

namespace PerronVariationalChallenge

/-- The Euclidean space `ℝᵈ`. -/
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)

variable {d : ℕ}

/-! ### The domain -/

/-- The positivity set `{u > 0}` of `u` inside the domain `U`. -/
def posSet (u : E d → ℝ) (U : Set (E d)) : Set (E d) := {x ∈ U | 0 < u x}

/-- The free boundary `∂{u > 0} ∩ U`. -/
def freeBoundary (u : E d → ℝ) (U : Set (E d)) : Set (E d) := frontier (posSet u U) ∩ U

/-- `U` has `C²` boundary, encoded by a global `C²` defining function: `U = {ρ < 0}` with
`∇ρ ≠ 0` on `∂U`. -/
def HasC2Boundary (U : Set (E d)) : Prop :=
  ∃ ρ : E d → ℝ, ContDiff ℝ 2 ρ ∧ U = {x | ρ x < 0} ∧ ∀ x ∈ frontier U, ∇ ρ x ≠ 0

/-! ### Viscosity solutions ([AFS, Definition 2.1]) -/

/-- `φ` touches `u` from below in `S` at `x`: `x ∈ S`, `φ x = u x`, and `φ ≤ u` on a
neighbourhood of `x` relative to `S` (local, non-strict touching). -/
def TouchesBelow (φ u : E d → ℝ) (S : Set (E d)) (x : E d) : Prop :=
  x ∈ S ∧ φ x = u x ∧ ∀ᶠ y in 𝓝[S] x, φ y ≤ u y

/-- `φ` touches `u` from above in `S` at `x`: `x ∈ S`, `φ x = u x`, and `u ≤ φ` on a
neighbourhood of `x` relative to `S`. -/
def TouchesAbove (φ u : E d → ℝ) (S : Set (E d)) (x : E d) : Prop :=
  x ∈ S ∧ φ x = u x ∧ ∀ᶠ y in 𝓝[S] x, u y ≤ φ y

/-- [AFS, Definition 2.1(i)]. `u ∈ C(U)`, `u ≥ 0`, is a viscosity supersolution in `U`: whenever
a smooth `φ` touches `u` from below at `x ∈ U`, either `Δφ(x) ≤ 0`, or `φ(x) = 0` and
`|∇φ(x)| ≤ Q(x)`. The test functions `φ` are smooth on `ℝᵈ` (the paper: on `U`). -/
def IsViscSuper (U : Set (E d)) (Q u : E d → ℝ) : Prop :=
  ContinuousOn u U ∧ (∀ x ∈ U, 0 ≤ u x) ∧
    ∀ φ : E d → ℝ, ContDiff ℝ ∞ φ → ∀ x ∈ U, TouchesBelow φ u U x →
      Δ φ x ≤ 0 ∨ (φ x = 0 ∧ ‖∇ φ x‖ ≤ Q x)

/-- [AFS, Definition 2.1(ii)]. `u ∈ C(U)`, `u ≥ 0`, is a viscosity subsolution in `U`: whenever
`φ` is smooth and `φ₊ = max φ 0` touches `u` from above in `\overline{{u > 0}} ∩ U` at `x`, either
`Δφ(x) ≥ 0`, or `φ(x) = 0` and `|∇φ(x)| ≥ Q(x)`. The test functions `φ` are smooth on `ℝᵈ`. -/
def IsViscSub (U : Set (E d)) (Q u : E d → ℝ) : Prop :=
  ContinuousOn u U ∧ (∀ x ∈ U, 0 ≤ u x) ∧
    ∀ φ : E d → ℝ, ContDiff ℝ ∞ φ → ∀ x,
      TouchesAbove (fun y ↦ max (φ y) 0) u (closure (posSet u U) ∩ U) x →
        0 ≤ Δ φ x ∨ (φ x = 0 ∧ Q x ≤ ‖∇ φ x‖)

/-! ### Smooth strict sub- and supersolutions ([AFS, Definition 2.2]) -/

/-- [AFS, Definition 2.2]. `g` is a smooth strict subsolution: `g` is `C²` (on `ℝᵈ`; the paper:
on `Ū`) and there are `a₀, δ₀ > 0` with (i) `Δg ≥ 0` on `{g > -a₀}` and
(ii) `|∇g|² ≥ (1 + δ₀) Q²` on `{|g| ≤ a₀}`, both sets taken inside `Ū`. -/
def IsStrictSub (U : Set (E d)) (Q g : E d → ℝ) : Prop :=
  ContDiff ℝ 2 g ∧ ∃ a₀ > 0, ∃ δ₀ > 0,
    (∀ x ∈ closure U, -a₀ < g x → 0 ≤ Δ g x) ∧
    ∀ x ∈ closure U, |g x| ≤ a₀ → (1 + δ₀) * Q x ^ 2 ≤ ‖∇ g x‖ ^ 2

/-- [AFS, Definition 2.2]. `g` is a smooth strict supersolution: `g` is `C²` and there are
`a₀, δ₀ > 0` with (i) `Δg ≤ 0` on `{g > -a₀}` and (ii) `|∇g|² ≤ (1 - δ₀) Q²` on `{|g| ≤ a₀}`,
both sets taken inside `Ū`. -/
def IsStrictSuper (U : Set (E d)) (Q g : E d → ℝ) : Prop :=
  ContDiff ℝ 2 g ∧ ∃ a₀ > 0, ∃ δ₀ > 0,
    (∀ x ∈ closure U, -a₀ < g x → Δ g x ≤ 0) ∧
    ∀ x ∈ closure U, |g x| ≤ a₀ → ‖∇ g x‖ ^ 2 ≤ (1 - δ₀) * Q x ^ 2

/-! ### Perron's method ([AFS, (2.1)–(2.4)]) -/

/-- The class `𝒮_g` of [AFS, (2.3)]: the functions `v ∈ C(Ū)` that are viscosity supersolutions
in `U` with `v ≥ g₊` on `Ū`. -/
def perronSuperClass (U : Set (E d)) (Q g : E d → ℝ) : Set (E d → ℝ) :=
  {v | ContinuousOn v (closure U) ∧ IsViscSuper U Q v ∧ ∀ x ∈ closure U, max (g x) 0 ≤ v x}

/-- The smallest supersolution above `g` [AFS, (2.4)]: `u(x) = inf_{v ∈ 𝒮_g} v(x)`, as a real
infimum (`sInf`). Only its values on `Ū` enter the claims. -/
def perronSmallest (U : Set (E d)) (Q g : E d → ℝ) (x : E d) : ℝ :=
  sInf ((fun v ↦ v x) '' perronSuperClass U Q g)

/-- The class `𝒮^g` of [AFS, (2.1)]: the functions `v ∈ C(Ū)` that are viscosity subsolutions in
`U` with `v ≤ g₊` on `Ū`. -/
def perronSubClass (U : Set (E d)) (Q g : E d → ℝ) : Set (E d → ℝ) :=
  {v | ContinuousOn v (closure U) ∧ IsViscSub U Q v ∧ ∀ x ∈ closure U, v x ≤ max (g x) 0}

/-- The largest subsolution below `g` [AFS, (2.2)]: `u(x) = sup_{v ∈ 𝒮^g} v(x)`, as a real
supremum (`sSup`). Only its values on `Ū` enter the claims. -/
def perronLargest (U : Set (E d)) (Q g : E d → ℝ) (x : E d) : ℝ :=
  sSup ((fun v ↦ v x) '' perronSubClass U Q g)

/-! ### Blow-ups and classical solutions ([AFS, Corollary 1.2]) -/

/-- The blow-up `u_{x₀,r}(y) = r⁻¹ u(x₀ + r y)`. -/
def blowup (u : E d → ℝ) (x₀ : E d) (r : ℝ) (y : E d) : ℝ :=
  u (x₀ + r • y) / r

/-- `v` is a (subsequential) blow-up limit of `u` at `x₀`: `u_{x₀,r_n} → v` locally uniformly on
`ℝᵈ` along some sequence `r_n → 0⁺`. -/
def IsBlowupLimit (u : E d → ℝ) (x₀ : E d) (v : E d → ℝ) : Prop :=
  ∃ r : ℕ → ℝ, (∀ n, 0 < r n) ∧ Tendsto r atTop (𝓝 0) ∧
    TendstoLocallyUniformly (fun n ↦ blowup u x₀ (r n)) v atTop

/-- `S` is a `C^{1,γ}` hypersurface in `B_r(x₀)`: for some `γ ∈ (0, 1]`, unit vector `e`, and
`C¹` function `f` whose derivative is `γ`-Hölder, `S ∩ B_r(x₀)` is the graph
`{y : (y - x₀) · e = f(P(y - x₀))}` over the hyperplane `e^⊥`, where `P z = z - (z · e) e` is the
orthogonal projection onto `e^⊥`. -/
def IsC1GammaHypersurfaceNear (S : Set (E d)) (x₀ : E d) (r : ℝ) : Prop :=
  ∃ γ : ℝ≥0, 0 < γ ∧ γ ≤ 1 ∧ ∃ e : E d, ‖e‖ = 1 ∧ ∃ (f : E d → ℝ) (C : ℝ≥0),
    ContDiff ℝ 1 f ∧ HolderWith C γ (fderiv ℝ f) ∧
    S ∩ ball x₀ r =
      {y ∈ ball x₀ r | inner ℝ (y - x₀) e = f (y - x₀ - inner ℝ (y - x₀) e • e)}

/-- `u` is a classical solution of [AFS, (1.1)] near the free boundary point `x₀`
([AFS, Corollary 1.2, footnote]): for some `r > 0` with `B_r(x₀) ⊆ U`,
* the free boundary `∂{u > 0} ∩ U` is a `C^{1,γ}` hypersurface in `B_r(x₀)`;
* `u` is `C²` and harmonic in `{u > 0} ∩ B_r(x₀)`;
* `∇u` extends continuously (as `G`) to `\overline{{u > 0}} ∩ B_r(x₀)`, and the free boundary
  condition `|∇u| = Q` holds at every point of `∂{u > 0} ∩ B_r(x₀)`. -/
def IsClassicalNear (U : Set (E d)) (Q u : E d → ℝ) (x₀ : E d) : Prop :=
  ∃ r > 0, ball x₀ r ⊆ U ∧ IsC1GammaHypersurfaceNear (freeBoundary u U) x₀ r ∧
    ContDiffOn ℝ 2 u (posSet u U ∩ ball x₀ r) ∧ (∀ y ∈ posSet u U ∩ ball x₀ r, Δ u y = 0) ∧
    ∃ G : E d → E d, ContinuousOn G (closure (posSet u U) ∩ ball x₀ r) ∧
      (∀ y ∈ posSet u U ∩ ball x₀ r, G y = ∇ u y) ∧
      ∀ y ∈ freeBoundary u U ∩ ball x₀ r, ‖G y‖ = Q y

/-! ### The claims -/

/-- **[AFS, Corollary 1.2(i)]**. Let `U ⊆ ℝ²` be open, bounded and connected with `C²` boundary,
and `Q` Lipschitz on `Ū` with `0 < Q_min ≤ Q ≤ Q_max` on `Ū`. Let `u` be the smallest
supersolution above a smooth strict subsolution `g` with `g > 0` on `∂U`. Then the free boundary
`∂{u > 0} ∩ U` is the disjoint union of `FB_reg` and `FB_TP`, where `FB_reg` is relatively open in
the free boundary and `u` is a classical solution near each of its points, and at each
`x₀ ∈ FB_TP` every subsequential blow-up limit of `u` is `y ↦ Q(x₀) |y · e|` for some unit vector
`e` (in the blow-up variable `y`; the paper writes `Q(x₀) |(x - x₀) · e|`). -/
def Corollary2DSmallestClaim : Prop :=
  ∀ (U : Set (E 2)) (Q : E 2 → ℝ) (Qmin Qmax : ℝ),
    IsOpen U → Bornology.IsBounded U → IsConnected U → HasC2Boundary U →
    (∃ K, LipschitzOnWith K Q (closure U)) → 0 < Qmin → Qmin ≤ Qmax →
    (∀ x ∈ closure U, Qmin ≤ Q x ∧ Q x ≤ Qmax) →
    ∀ g : E 2 → ℝ, IsStrictSub U Q g → (∀ x ∈ frontier U, 0 < g x) →
      ∃ FBreg FBtp : Set (E 2),
        Disjoint FBreg FBtp ∧
        FBreg ∪ FBtp = freeBoundary (perronSmallest U Q g) U ∧
        (∃ O : Set (E 2), IsOpen O ∧ FBreg = O ∩ freeBoundary (perronSmallest U Q g) U) ∧
        (∀ x₀ ∈ FBreg, IsClassicalNear U Q (perronSmallest U Q g) x₀) ∧
        ∀ x₀ ∈ FBtp, ∀ v : E 2 → ℝ, IsBlowupLimit (perronSmallest U Q g) x₀ v →
          ∃ e : E 2, ‖e‖ = 1 ∧ ∀ y, v y = Q x₀ * |inner ℝ y e|

/-- **[AFS, Corollary 1.2(ii)]**. Under the assumptions on `U ⊆ ℝ²` and `Q` of
`Corollary2DSmallestClaim`, let `u` be the largest subsolution below a smooth strict supersolution
`g`. Then `u` is a classical solution of [AFS, (1.1)] in `U`: it is a classical solution near
every free boundary point. -/
def Corollary2DLargestClaim : Prop :=
  ∀ (U : Set (E 2)) (Q : E 2 → ℝ) (Qmin Qmax : ℝ),
    IsOpen U → Bornology.IsBounded U → IsConnected U → HasC2Boundary U →
    (∃ K, LipschitzOnWith K Q (closure U)) → 0 < Qmin → Qmin ≤ Qmax →
    (∀ x ∈ closure U, Qmin ≤ Q x ∧ Q x ≤ Qmax) →
    ∀ g : E 2 → ℝ, IsStrictSuper U Q g →
      ∀ x₀ ∈ freeBoundary (perronLargest U Q g) U, IsClassicalNear U Q (perronLargest U Q g) x₀

/-- **Model example: a two-plane point, and distinct extremal solutions.** Not a result of
[AFS]; it shows that the two cases of [AFS, Theorem 1.1] can produce different solutions from the
same boundary data, and that the second alternative of [AFS, Corollary 1.2(i)] (a point where every
blow-up is a two-plane solution) occurs.

In `ℝ²` with `Q ≡ 1` there are a domain `U` and data `g_sub`, `g_super` such that
* `U`, `Q`, `g_sub` satisfy the hypotheses of `Corollary2DSmallestClaim`, and `U`, `Q`, `g_super`
  those of `Corollary2DLargestClaim` (except the trivial ones: for `Q ≡ 1` with
  `Q_min = Q_max = 1`, the bounds `0 < Q_min ≤ Q ≤ Q_max`);
* `g_sub = g_super` on `∂U`: the two problems have the same boundary data;

and, writing `u_min = perronSmallest U 1 g_sub` and `u_max = perronLargest U 1 g_super`:
1. `u_min` and `u_max` are nontrivial: each is positive at some point of `U`, vanishes at some
   point of `U`, and has a nonempty free boundary;
2. `0` is a two-plane point of `u_min`: `0 ∈ ∂{u_min > 0} ∩ U`, the blow-ups `(u_min)_{0,t}`
   converge to `y ↦ |y₁|` locally uniformly on `ℝ²` as `t → 0⁺`, and every blow-up limit of
   `u_min` at `0` is `y ↦ |y₁|`, where `y₁ = ⟪y, e₁⟫`;
3. `u_min ≠ u_max`: they differ at some point of `U` (values outside `U` are irrelevant).

The construction behind the solution: `U = B₁(0) \ (B̄_{a/2}(a e₁) ∪ B̄_{a/2}(-a e₁))` for a small
`a > 0`, with data equal to `a log 2` on both inner circles, so that the radial solutions
`(a log (a / |x ∓ a e₁|))₊` from the two holes have free boundaries `∂B_a(± a e₁)`, which touch at
`0`. The claim itself is existential and does not fix the construction. -/
def ModelExampleClaim : Prop :=
  ∃ (U : Set (E 2)) (gsub gsuper : E 2 → ℝ),
    IsOpen U ∧ Bornology.IsBounded U ∧ IsConnected U ∧ HasC2Boundary U ∧
    (∃ K, LipschitzOnWith K (fun _ : E 2 ↦ (1 : ℝ)) (closure U)) ∧
    IsStrictSub U (fun _ ↦ 1) gsub ∧ (∀ x ∈ frontier U, 0 < gsub x) ∧
    IsStrictSuper U (fun _ ↦ 1) gsuper ∧
    (∀ x ∈ frontier U, gsub x = gsuper x) ∧
    (∃ x ∈ U, 0 < perronSmallest U (fun _ ↦ 1) gsub x) ∧
    (∃ x ∈ U, perronSmallest U (fun _ ↦ 1) gsub x = 0) ∧
    (freeBoundary (perronSmallest U (fun _ ↦ 1) gsub) U).Nonempty ∧
    (∃ x ∈ U, 0 < perronLargest U (fun _ ↦ 1) gsuper x) ∧
    (∃ x ∈ U, perronLargest U (fun _ ↦ 1) gsuper x = 0) ∧
    (freeBoundary (perronLargest U (fun _ ↦ 1) gsuper) U).Nonempty ∧
    (0 : E 2) ∈ freeBoundary (perronSmallest U (fun _ ↦ 1) gsub) U ∧
    TendstoLocallyUniformly (fun t ↦ blowup (perronSmallest U (fun _ ↦ 1) gsub) 0 t)
      (fun y ↦ |inner ℝ y (EuclideanSpace.single 0 1)|) (𝓝[>] 0) ∧
    (∀ v, IsBlowupLimit (perronSmallest U (fun _ ↦ 1) gsub) 0 v →
      ∀ y, v y = |inner ℝ y (EuclideanSpace.single 0 1)|) ∧
    ∃ x ∈ U, perronSmallest U (fun _ ↦ 1) gsub x ≠ perronLargest U (fun _ ↦ 1) gsuper x

end PerronVariationalChallenge

end
-- END GENERATED VOCABULARY

/-! # Challenge: Corollary 1.2, the free boundary of extremal solutions in the plane, and a model
example (vocabulary: `Vocabulary.lean`) -/

open PerronVariationalChallenge

theorem challenge_corollary_2d_smallest : Corollary2DSmallestClaim := by
  sorry

theorem challenge_corollary_2d_largest : Corollary2DLargestClaim := by
  sorry

/-- **Non-vacuity check (a model example), not a result of the paper.** In `ℝ²` with `Q ≡ 1`, one
domain and one boundary condition give a smallest supersolution `u_min` and a largest subsolution
`u_max` that are both nontrivial, with nonempty free boundaries, and differ; and `0` is a two-plane
point of `u_min` (see `ModelExampleClaim`).

What it guards against: vacuous or degenerate Perron classes and extremal solutions
(`perronSmallest`, `perronLargest`), and hypotheses on `U`, `Q` and `g` that no data satisfy. -/
theorem challenge_model_example : ModelExampleClaim := by
  sorry
